- hosts: myhost  # playbook to setup system as root
  become: true
  tasks:
    - name: Updates package lists for upgrades/new pkg, then upgrades all current packages to the latest version
      apt: upgrade=dist update_cache=yes
    - name: Install latest version of packages
      package: name="{{item}}" state=latest
      with_items:
        - python3-pip
        - virtualenv
        - git
        - nginx
        - fail2ban
        - libfontconfig  # needed for phantomjs
    - name: Add mongodb repo apt_key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
    - name: Add mongodb sources list
      shell: "echo 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list"
      changed_when: false
    - name: Update repositories cache and install "mongodb-org" package
      apt: name=mongodb-org update_cache=yes
    - name: Firewall turn on and allow OpenSSH
      ufw: rule=allow name=OpenSSH state=enabled
    - name: Firewall allow nginx https and http (for redirect to ssl)
      ufw: rule=allow name="Nginx Full"
- hosts: myhost  # playbook to setup code environment
  vars:
    githubuser: awcrosby@gmail.com
    services:
      - nginx
      - fail2ban
    newServices:
      - mongodb.service
      - media-search.service
  tasks:
    - name: Make project directory
      file: path=~/media-search/ state=directory
    - name: Git clone media-search repo
      git:
        repo: https://{{ githubuser | urlencode }}:{{ githubpw }}@github.com/awcrosby/media-search.git
        dest: ~/media-search
    - name: Create symlink for vim settings
      file:
        src: ~/media-search/config/.vimrc
        dest: ~/.vimrc
        state: link
    - name: Create virtual environment and install pip packages
      pip:
        requirements: ~/media-search/requirements.txt
        virtualenv: ~/media-search/venv
    - name: Copy nginx config to replace the default
      become: true
      copy:
        src: ~/media-search/config/nginx_config_pre_ssl
        dest: /etc/nginx/sites-available/default
    - name: Copy fail2ban config
      become: true
      copy:
        src: ~/media-search/config/jail.local
        dest: /etc/fail2ban/
    - name: Restart services
      become: true
      service: name="{{item}}" state=restarted
      changed_when: false
      with_items: "{{services}}"
    - name: Copy services
      become: true
      copy:
        src: ~/media-search/config/{{item}}
        dest: /etc/systemd/system/{{item}}
      with_items: "{{newServices}}"
    - name: Start and enable on startup the services
      become: true
      service: name="{{item}}" state=started enabled=yes
      with_items: "{{newServices}}"
    - name: Download phantomjs binary
      get_url:
        url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
        dest: ~/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - name: Extract phantomjs tar
      unarchive:
        src: ~/phantomjs-2.1.1-linux-x86_64.tar.bz2
        dest: ~/
        remote_src: yes
    - name: Copy phantomjs to dir in PATH variable
      copy:
        src: ~/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
        dest: ~/media-search/venv/bin/phantomjs
        mode: u=rwx,g=rx,o=rx
        remote_src: yes
